# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [manual]

repos:

  # GLOBAL LINTING
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Checks yaml files for parsable syntax.
      - id: check-json # Checks json files for parsable syntax.
      - id: check-added-large-files # Checks for large files that bloat the git repository
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.

  # PYTHON LINTING
  - repo: local
    hooks:
      - id: black
        name: black
        types: [file, python]
        language: system
        entry: black

      - id: isort
        name: isort
        types: [file, python]
        language: system
        entry: isort

      - id: flake8
        name: Flake8
        types: [file, python]
        language: system
        entry: flake8

      - id: pylint-src
        name: pylint on src*
        types: [file, python]
        language: system
        entry: pylint --disable=too-few-public-methods,logging-fstring-interpolation,f-string-without-interpolation,no-member,broad-except --enable=W0614

      - id: pylint-tests
        name: pylint on tests*
        language: system
        entry: pylint --disable=invalid-name,missing-docstring,too-many-function-args,unused-variable,fixme,abstract-class-instantiated,no-self-use,too-few-public-methods